# version de Docker compose que l'on souhaite utiliser
version: "3.1"


# Ensuite on crée des services
services:
    # POSTGRESQL
    database:
        image: "postgres:latest"
        restart: "unless-stopeed" #always, never, ...
        environment: 
            POSTGRES_DB: "courswsf"
            POSTGRES_USER: "kevin"
            POSTGRES_PASSWORD: "azerty"
        volumes: 
            - "dbsql:/var/lib/postegresql/data" #on donne un nom a un volume : cours, et qui récup les datas dans var/lib, ... (DONNÉES PERSISTANTES)
        ports:
            - "5432:5432" #port à l'intérieur du réseau local (docker) /// (après les ":") = port sur lequel on va exposer

    # REDIS
    redis:
        image: redis:latest
        volumes:
            - "redis-data:/data"
        ports:
            - "6379:6379"   

volumes:
    dbsql:
    redis-data:
